# Generated by Django 3.2.18 on 2023-02-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sparepart',
            fields=[
                ('spid', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Số ID')),
                ('whloc', models.CharField(blank=True, choices=[('L', 'LONG PIPE'), ('S', 'SHORT PIPE')], default='S', max_length=1, null=True, verbose_name='Kho lưu trữ')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên gọi')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Spare part list',
                'verbose_name_plural': '1. Danh mục phụ tùng',
            },
        ),
        migrations.CreateModel(
            name='exportnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doexp', models.DateField(blank=True, null=True, verbose_name='Ngày xuất')),
                ('purpose', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mục đích sử dụng')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('spid', models.ForeignKey(default=None, max_length=25, on_delete=django.db.models.deletion.CASCADE, to='spwh.sparepart', verbose_name='Spare Part ID')),
            ],
        ),
    ]
