# Generated by Django 3.2.18 on 2023-02-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportnote',
            options={'verbose_name': 'Export notice', 'verbose_name_plural': '2. Phiếu xuất kho'},
        ),
    ]
