# Generated by Django 3.2.18 on 2023-02-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0004_alter_exportnote_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='fullname',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='ename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên gọi tiếng Anh'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='vname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên gọi tiếng Việt'),
        ),
    ]
