# Generated by Django 3.2.18 on 2023-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0005_auto_20230222_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='spec',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SPEC'),
        ),
    ]
