# Generated by Django 3.2.18 on 2023-02-23 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0006_sparepart_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportnote',
            name='doexp',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày xuất'),
        ),
    ]
