# Generated by Django 3.2.18 on 2023-02-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0007_alter_exportnote_doexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportnote',
            name='expmc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Máy xuất kho'),
        ),
    ]
