# Generated by Django 3.2.18 on 2023-02-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0008_exportnote_expmc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportnote',
            options={'verbose_name': 'Export notice', 'verbose_name_plural': 'Phiếu xuất kho'},
        ),
        migrations.AlterModelOptions(
            name='sparepart',
            options={'verbose_name': 'Spare part list', 'verbose_name_plural': 'Danh mục phụ tùng'},
        ),
    ]
