# Generated by Django 3.2.18 on 2023-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0010_alter_sparepart_whloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='whloc',
            field=models.CharField(blank=True, choices=[('L', 'PI'), ('S', 'PR')], default='S', max_length=1, null=True, verbose_name='Tên kho'),
        ),
    ]
