# Generated by Django 3.2.18 on 2023-02-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0012_alter_exportnote_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportnote',
            name='qty',
            field=models.CharField(default='1', max_length=255, null=True, verbose_name='Số lượng xuất kho'),
        ),
    ]
