# Generated by Django 3.2.18 on 2023-02-26 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0014_alter_exportnote_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportnote',
            name='doexp',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày xuất kho'),
        ),
        migrations.AlterField(
            model_name='exportnote',
            name='spid',
            field=models.ForeignKey(default=None, max_length=25, on_delete=django.db.models.deletion.CASCADE, to='spwh.sparepart', verbose_name='Mã sản phẩm'),
        ),
    ]
