# Generated by Django 3.2.18 on 2023-02-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0015_auto_20230226_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportnote',
            name='qty',
            field=models.IntegerField(default='1', null=True, verbose_name='Số lượng xuất kho'),
        ),
    ]
