# Generated by Django 3.2.18 on 2023-02-27 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0016_alter_exportnote_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('secid', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Bộ phận sử dụng')),
                ('secname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên gọi')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Section list',
                'verbose_name_plural': 'Bộ phận sử dụng',
            },
        ),
        migrations.AddField(
            model_name='exportnote',
            name='secid',
            field=models.ForeignKey(default=None, max_length=25, on_delete=django.db.models.deletion.CASCADE, to='spwh.section', verbose_name='Bộ phận sử dụng'),
        ),
    ]
