# Generated by Django 3.2.18 on 2023-02-27 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0017_auto_20230227_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportnote',
            name='secid',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='spwh.section', verbose_name='Bộ phận sử dụng'),
        ),
    ]
