# Generated by Django 3.2.18 on 2023-02-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spwh', '0019_alter_exportnote_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportnote',
            name='expmc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QR Scanner'),
        ),
    ]
